# Use root/password from ./secrets/pwdfile as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/user
      MYSQL_DATABASE: testdb
    expose:
      - '3306'
    volumes:
      - ./Mysql/secrets:/run/secrets

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1