apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-autoscaling
  labels:
    app: k8s-deployment
    owner: bokhanych
spec: 
  replicas: 2
  selector:
    matchLabels:
      project: project_rep_autoscaling
  template:
    metadata:
      labels:
        project: project_rep_autoscaling   
    spec:
      containers:
        - name: webserver-autoscaling
          image: nginx:latest
          ports:
            - containerPort: 80


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webserver-autoscaling
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
