version: "3"

services:

  nginx:
    build: ./nginx/
    ports:
      - "8080:80"
      - "8043:443"
    volumes:
      - ./nginx/logs:/opt/nginx/logs

  apache:
    build: ./apache/
    ports:
        - "8180:80"
        - "8143:443"
    volumes:
      - ./apache/logs:/opt/apache/logs      