#Download base image ubuntu 20.04
FROM centos:7

# LABEL about the custom image
LABEL description="Centos + Nginx"

# Update and install nginx
RUN yum -y install epel-release && yum -y update && yum -y install nginx

# Create custom index.html
RUN echo '<h1>Centos + Nginx</h1>' > /usr/share/nginx/html/index.html

# Expose Port for the Application
EXPOSE 80

# RUN VASYA, RUN
CMD ["nginx", "-g", "daemon off;"]                          