#Download base image ubuntu 20.04
FROM ubuntu:20.04

# LABEL about the custom image
LABEL description="Ubuntu + Apache2"

# Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

# Update and install nginx
RUN apt update && apt install -y apache2 && apt clean

# Create custom index.html
RUN echo '<h1>Ubuntu + Apache2</h1>' > /var/www/html/index.html

# Expose Port for the Application
EXPOSE 80

# RUN VASYA, RUN
CMD ["/usr/sbin/apache2ctl", "-D","FOREGROUND"]