Vagrant.configure("2") do |config|

	config.vm.define "docker" do |docker|
		docker.vm.box = "ubuntu/jammy64"
		docker.vm.box_check_update = false
		docker.vm.hostname="docker"
		docker.vm.network "private_network", ip: "10.0.0.10"
		docker.vm.provision "shell", inline: <<-SHELL

sudo curl -fsSL https://get.docker.com | sh
sudo mkdir /root/html
sudo docker run -dit --name itisgood-web -p 8082:80 -v /root/html/:/usr/local/apache2/htdocs/ httpd:2.4
sudo cat << EOF > /root/html/index.html
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=windows-1251"><meta name="color-scheme" content="light dark"></head>
<body> 
<h1>ПРЕВЕД МЕДВЕД</h1>
</body>
</html>
EOF

		SHELL
		docker.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "docker"]
			vb.customize ["modifyvm", :id, "--memory", "1024"]
		end
	end

end