version: "3"

services:

  nginx:
    image: nginx
    container_name: bokhanych_nginx
    restart: always
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    networks:
      - tmsnet

  apache:
    image: httpd:2.4
    container_name: bokhanych_apache
    restart: always
    volumes:
      - ./apache/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      - tmsnet

  haproxy:
    image: haproxy:2.3
    container_name: bokhanych_haproxy
    restart: always
    volumes:
      - ./haproxy/ssl/site.pem:/etc/ssl/certs/site.pem
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - nginx
      - apache
    networks:
      - tmsnet
    ports:
      - "8080:443"

  nginx-proxy:
    image: nginx
    container_name: bokhanych_nginx-proxy
    links:
      - nginx
      - apache
      - haproxy
    restart: always
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-proxy/index.html:/usr/share/nginx/html/index.html
      - ./nginx-proxy/ssl/site.crt:/etc/nginx/ssl/site.crt
      - ./nginx-proxy/ssl/site.key:/etc/nginx/ssl/site.key
    ports:
      - "443:443"

networks:
        tmsnet: