---
# tasks file for deploy_apache_web
- block: #for CentOS
  - name: "Install Httpd"
    yum: name=httpd state=latest

  - name: "Copy new page to Centos Server"
    copy: src=index.html dest={{ destin_file }} mode=0555
    notify: Restart httpd

  - name: "Start httpd and make it enable on boot"
    service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- block: #for Debian
  - name: "Install Apache2"
    apt: name=apache2 update_cache=yes state=latest

  - name: "Copy new page to Debian Server"
    copy: src=index.html dest={{ destin_file }} mode=0555
    notify: Restart apache2

  - name: "Start apache2 and make it enable on boot"
    service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"