# Use root/password from ./secrets/pwdfile as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/pwdfile
    expose:
      - '3306'
    volumes:
      - ./secrets:/run/secrets

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080